-- Постраничный просмотр polars DataFrame из ядра molten в полноэкранной
-- вкладке (по мотивам dbee-layout). Данные живут в ядре Jupyter, поэтому каждая
-- страница — это slice(offset, PAGE) в самом ядре: оно форматирует таблицу
-- и атомарно пишет в temp-файл, nvim только ждёт файл и рендерит текст.
-- Канал к ядру — :MoltenEvaluateArgument exec(open(<script>).read()).
--
-- Нюанс: выражение пересчитывается на каждой странице (df.filter(...) для
-- тяжёлых фильтров лучше сначала положить в переменную в ноутбуке).

local M = {}

local PAGE = 50 -- строк на страницу
local TIMEOUT_MS = 15000 -- ожидание ответа ядра (оно может быть занято ячейкой)
local POLL_MS = 100

local state = {
    src_win = nil, -- окно ноутбука: ядро molten привязано к его буферу
    buf = nil,
    win = nil,
    expr = nil,
    offset = 0,
    total = nil,
    waiting = false,
}

-- python-сниппет, выполняемый в ядре: срез + формат + атомарная запись.
-- Все имена с префиксом _mt_, в конце подчищаются из globals().
local function py_script(expr, offset, out_path)
    return table.concat({
        "# auto-generated by molten_table.lua",
        "import json as _mt_json, os as _mt_os, traceback as _mt_tb",
        string.format("_mt_out = r'%s'", out_path),
        "_mt_tmp = _mt_out + '.tmp'",
        "try:",
        "    import polars as _mt_pl",
        string.format("    _mt_obj = (%s)", expr),
        "    if not isinstance(_mt_obj, _mt_pl.DataFrame):",
        "        raise TypeError('ожидался polars.DataFrame, получен ' + type(_mt_obj).__name__)",
        "    _mt_total = _mt_obj.height",
        string.format("    _mt_page = _mt_obj.slice(%d, %d)", offset, PAGE),
        string.format(
            -- tbl_width_chars ограничен u16 в polars — 100000 паникует
            "    with _mt_pl.Config(tbl_rows=%d, tbl_cols=-1, tbl_width_chars=65000, fmt_str_lengths=120, tbl_hide_dataframe_shape=True):",
            PAGE
        ),
        "        _mt_text = str(_mt_page)",
        string.format(
            "    _mt_body = _mt_json.dumps({'ok': True, 'total': _mt_total, 'offset': %d}) + '\\n' + _mt_text",
            offset
        ),
        "except Exception as _mt_e:",
        "    _mt_body = _mt_json.dumps({'ok': False, 'error': ''.join(_mt_tb.format_exception_only(type(_mt_e), _mt_e)).strip()})",
        "with open(_mt_tmp, 'w') as _mt_f:",
        "    _mt_f.write(_mt_body)",
        "_mt_os.replace(_mt_tmp, _mt_out)",
        "for _mt_k in [_k for _k in list(globals()) if _k.startswith('_mt_')]:",
        "    del globals()[_mt_k]",
        "del _mt_k",
    }, "\n")
end

-- отправить запрос страницы в ядро и дождаться файла-ответа
local function kernel_request(expr, offset, cb)
    if state.waiting then
        vim.notify("molten-table: предыдущий запрос ещё выполняется", vim.log.levels.WARN)
        return
    end
    local out = vim.fn.tempname() .. ".mt"
    local script = vim.fn.tempname() .. ".py"
    vim.fn.writefile(vim.split(py_script(expr, offset, out), "\n", { plain = true }), script)

    local ok, err = pcall(function()
        -- код гоним из окна ноутбука: molten ищет ядро по текущему буферу
        vim.api.nvim_win_call(state.src_win, function()
            vim.cmd(("MoltenEvaluateArgument exec(open(r'%s').read())"):format(script))
        end)
    end)
    if not ok then
        vim.fn.delete(script)
        vim.notify(
            "molten-table: не удалось выполнить код в ядре (ядро не запущено? <leader>ji)\n" .. tostring(err),
            vim.log.levels.ERROR
        )
        return
    end

    state.waiting = true
    local waited = 0
    local timer = vim.uv.new_timer()
    timer:start(
        POLL_MS,
        POLL_MS,
        vim.schedule_wrap(function()
            if vim.fn.filereadable(out) == 1 then
                timer:stop()
                timer:close()
                state.waiting = false
                local lines = vim.fn.readfile(out)
                vim.fn.delete(out)
                vim.fn.delete(script)
                local meta_ok, meta = pcall(vim.json.decode, lines[1] or "")
                if not meta_ok or type(meta) ~= "table" then
                    vim.notify("molten-table: битый ответ ядра", vim.log.levels.ERROR)
                    return
                end
                if meta.ok then
                    cb(meta, vim.list_slice(lines, 2, #lines))
                else
                    vim.notify("molten-table: " .. (meta.error or "ошибка в ядре"), vim.log.levels.ERROR)
                end
                return
            end
            waited = waited + POLL_MS
            if waited >= TIMEOUT_MS then
                timer:stop()
                timer:close()
                state.waiting = false
                vim.fn.delete(script)
                vim.notify(
                    "molten-table: таймаут — ядро занято (бежит ячейка?) или запрос упал",
                    vim.log.levels.ERROR
                )
            end
        end)
    )
end

local function last_page_offset()
    if not state.total or state.total == 0 then
        return 0
    end
    return math.floor((state.total - 1) / PAGE) * PAGE
end

local function set_header()
    local from = (state.total == 0) and 0 or state.offset + 1
    local to = math.min(state.offset + PAGE, state.total or 0)
    local page_no = math.floor(state.offset / PAGE) + 1
    local pages = math.floor(last_page_offset() / PAGE) + 1
    local s = string.format(
        "%s · строки %d–%d из %d · стр. %d/%d · [H]/[L] страницы · [[ / ]] края · [R] обновить · [q] закрыть",
        state.expr,
        from,
        to,
        state.total or 0,
        page_no,
        pages
    )
    vim.wo[state.win].winbar = s:gsub("%%", "%%%%")
end

local function ensure_window()
    if state.buf == nil or not vim.api.nvim_buf_is_valid(state.buf) then
        state.buf = vim.api.nvim_create_buf(false, true) -- scratch
        vim.bo[state.buf].bufhidden = "hide"
        vim.bo[state.buf].filetype = "molten_table"
        local bmap = function(lhs, fn, desc)
            vim.keymap.set("n", lhs, fn, { buffer = state.buf, silent = true, desc = desc })
        end
        -- пагинация в стиле dbee: H/L страницы, [[ / ]] первая/последняя
        bmap("L", function()
            M.page(state.offset + PAGE)
        end, "molten-table: следующая страница")
        bmap("H", function()
            M.page(state.offset - PAGE)
        end, "molten-table: предыдущая страница")
        bmap("[[", function()
            M.page(0)
        end, "molten-table: первая страница")
        bmap("]]", function()
            M.page(math.huge)
        end, "molten-table: последняя страница")
        bmap("R", function()
            M.page(state.offset)
        end, "molten-table: обновить страницу")
        bmap("q", function()
            M.close()
        end, "molten-table: закрыть")
    end
    if state.win == nil or not vim.api.nvim_win_is_valid(state.win) then
        -- на весь экран (как layout dbee): отдельная вкладка, q закрывает её
        -- и возвращает ноутбук нетронутым. "tab split", а не "tabnew" — чтобы
        -- не плодить пустые [No Name]-буферы.
        vim.cmd("tab split")
        state.win = vim.api.nvim_get_current_win()
        vim.api.nvim_win_set_buf(state.win, state.buf)
        vim.wo[state.win].wrap = false -- широкие таблицы — горизонтальный скролл
        vim.wo[state.win].number = false
        vim.wo[state.win].relativenumber = false
        vim.wo[state.win].signcolumn = "no"
        vim.wo[state.win].cursorline = true
    end
end

local function render(meta, body)
    state.total = meta.total
    state.offset = meta.offset
    ensure_window()
    vim.bo[state.buf].modifiable = true
    vim.api.nvim_buf_set_lines(state.buf, 0, -1, false, body)
    vim.bo[state.buf].modifiable = false
    set_header()
    vim.api.nvim_set_current_win(state.win) -- фокус в drawer: скроллить/искать
end

-- запросить страницу с указанным offset (клампится в [0, последняя])
function M.page(offset)
    if not state.expr then
        vim.notify("molten-table: сначала открой таблицу (<leader>jt)", vim.log.levels.WARN)
        return
    end
    offset = math.max(0, math.min(offset, last_page_offset()))
    kernel_request(state.expr, offset, render)
end

-- точка входа: спросить выражение и показать первую страницу
function M.open()
    state.src_win = vim.api.nvim_get_current_win()
    local default = vim.fn.expand("<cword>")
    if default == "" then
        default = "df_temp"
    end
    local expr = vim.fn.input({ prompt = "DataFrame: ", default = default, cancelreturn = "" })
    if expr == "" then
        return
    end
    state.expr = expr
    state.total = nil
    kernel_request(expr, 0, render)
end

function M.close()
    if state.win and vim.api.nvim_win_is_valid(state.win) then
        vim.api.nvim_win_close(state.win, true)
    end
    state.win = nil
end

return M
